version: '2'

services:
  sdsk:
    image: a347807131/scrapyd-spiderkeeper
    volumes:
      - /volume/scrapyd:/var/lib/scrapyd
    ports:
      - 5000:5000
    environment:
      - SK_USERNAME=admin
      - SK_PASSWORD=admin
